package com.qaprosoft.puma.mobile.gui.pages.android;

public enum States {
    ALABAMA("Alabama"),
    ALASKA("Alaska"),
    AMERICAN_SAMOA("American Samoa"),
    ARIZONA("Arizona"),
    ARKANSAS("Arkansas"),
    CALIFORNIA("California"),
    COLORADO("Colorado"),
    CONNECTICUT("Connecticut"),
    DELAWARE("Delaware"),
    DISTRICT_OF_COLUMBIA("District of Columbia"),
    FLORIDA("Florida"),
    GEORGIA("Georgia"),
    GUAM("Guam"),
    HAWAII("Hawaii"),
    IDAHO("Idaho"),
    ILLINOIS("Illinois"),
    INDIANA("Indiana"),
    IOWA("Iowa"),
    KANSAS("Kansas"),
    KENTUCKY("Kentucky"),
    LOUISIANA("Louisiana"),
    MAINE("Maine"),
    MARYLAND("Maryland"),
    MASSACHUSETTS("Massachusetts"),
    MICHIGAN("Michigan"),
    MINNESOTA("Minnesota"),
    MISSISSIPPI("Mississippi"),
    MISSOURI("Missouri"),
    MONTANA("Montana"),
    NEBRASKA("Nebraska"),
    NEVADA("Nevada"),
    NEW_HAMPSHIRE("New Hampshire"),
    NEW_JERSEY("New Jersey"),
    NEW_MEXICO("New Mexico"),
    NEW_YORK("New York"),
    NORTH_CAROLINA("North Carolina"),
    NORTH_DAKOTA("North Dakota"),
    NORTHERN_MARIANA_ISLANDS("Northern Mariana Islands"),
    OHIO("Ohio"),
    OKLAHOMA("Oklahoma"),
    OREGON("Oregon"),
    PENNSYLVANIA("Pennsylvania"),
    PUERTO_RICO("Puerto Rico"),
    RHODE_ISLAND("Rhode Island"),
    SOUTH_CAROLINA("South Carolina"),
    SOUTH_DAKOTA("South Dakota"),
    TENNESSEE("Tennessee"),
    TEXAS("Texas"),
    US_MINOR_OUTLYING_ISLANDS("US Minor Outlying Islands"),
    UTAH("Utah"),
    VERMONT("Vermont"),
    VIRGIN_ISLANDS_US("Virgin Islands, US"),
    VIRGINIA("Virginia"),
    WASHINGTON("Washington"),
    WEST_VIRGINIA("West Virginia"),
    WISCONSIN("Wisconsin"),
    WYOMING("Wyoming"),
    ARMED_FORCES_AFRICA("Armed Forces Africa"),
    ARMED_FORCES_AMERICA("Armed Forces America (exc Canada)"),
    ARMED_FORCES_CANADA("Armed Forces Canada"),
    ARMED_FORCES_EUROPE("Armed Forces Europe"),
    ARMED_FORCES_PACIFIC("Armed Forces Pacific"),
    ARMED_FORCES_MIDDLE_EAST("Armed Forces Middle East");
    private String state;

    States(String state) {
        this.state = state;
    }

    public String getState() {
        return state;
    }
}
